server:
  port: 8080

logging:
  level:
    root: DEBUG

netty:
  websocket:
    port: 1024
    ip: 0.0.0.0
    max-frame-size: 10240
    path: /channel

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    host: 47.113.201.150
    port: 5672
    virtual-host: /mfs
    username: root
    password: root
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 3000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
