server:
  port: 8080
logging:
  level:
    root: info

spring:
  main:
    web-application-type: reactive
    lazy-initialization: false

  rsocket:
    server:
      address: 0.0.0.0
      port: 9898
      # mapping-path: /rsocket/
      transport: tcp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mfs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true

  rabbitmq:
    host: 47.113.201.150
    port: 5672
    virtual-host: /mfs
    username: root
    password: root
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 500
          multiplier: 10.0
          max-interval: 10000
          max-attempts: 3
    stream:
      host: 47.113.201.150
      port: 5552
      username: root
      password: root
      name: mfs
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true

  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  integration:
    rsocket:
      server:
        message-mapping-enabled: false

influx:
  url: http://47.113.201.150:8086/
  username: root
  token: jcwsf_9hqdcC6fi9AiutB9tGmke2jX1QR2raCWHBS3Z5NDhupkMOqJ_NLgq0Vh5GBO3R-Ai_07XlntCEWSYsEA==
  org: example
  bucket: mfs
  logLevel: BODY
  readTimeout: 5s
  writeTimeout: 5s
  connectTimeout: 5s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: ASSIGN_UUID
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.edu.zut.mfs.dao
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml